spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file-upload
    username: postgres
    password: 1998
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
